import keyMirror from 'react/lib/keyMirror.js';

export default keyMirror({

  PAGE_INDEX_RESET: null,
  PAGE_INDEX_FETCH_SUCCESS: null,
  PAGE_INDEX_FETCH_FAIL: null,

  PAGE_FETCH_SUCCESS: null,
  PAGE_FETCH_FAIL: null,

  BLOG_INDEX_FETCH_SUCCESS: null,
  BLOG_INDEX_FETCH_FAIL: null,
  BLOG_FETCH_SUCCESS: null,
  BLOG_FETCH_FAIL: null,

  PORTFOLIO_INDEX_FETCH_SUCCESS: null,
  PORTFOLIO_INDEX_FETCH_FAIL: null,
  PORTFOLIO_FETCH_SUCCESS: null,
  PORTFOLIO_FETCH_FAIL: null,

  BLOGPAGE_FETCH_SUCCESS: null,
  BLOGPAGE_FETCH_FAIL: null,

  MENU_FETCH_SUCCESS: null,
  MENU_FETCH_FAIL: null,

  SITE_FETCH_SUCCESS: null,
  SITE_FETCH_FAIL: null,

  MENU_INDEX_FETCH_SUCCESS: null,
  MENU_INDEX_FETCH_FAIL: null,

  PROJECT_INDEX_FETCH_SUCCESS: null,
  PROJECT_INDEX_FETCH_FAIL: null,
  PROJECT_FETCH_SUCCESS: null,
  PROJECT_FETCH_FAIL: null,

  SITE_THEMECOLOR_SET: null,

});
